my_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - base_to_link1
    - link1_to_link2
  gains:
    base_to_link1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link1_to_link2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - link2_to_hand_base
    - left_gripper_joint
    - right_gripper_joint
  gains:
    link2_to_hand_base:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1